module.exports = [
  {
    list_id: 1,
    ingredient_name: "apple",
    qty: 10,
    unit_id: 1,
    category_id: 1,
  },
  {
    list_id: 1,
    ingredient_name: "berry",
    qty: 1,
    unit_id: 10,
    category_id: 1,
  },
  {
    list_id: 1,
    ingredient_name: "grape",
    qty: 1,
    unit_id: 10,
    category_id: 1,
  },
  {
    list_id: 1,
    ingredient_name: "broccoli",
    qty: 1,
    unit_id: 1,
    category_id: 2,
  },
  {
    list_id: 1,
    ingredient_name: "garlic",
    qty: 15,
    unit_id: 1,
    category_id: 2,
  },
  {
    list_id: 1,
    ingredient_name: "mushroom",
    qty: 1,
    unit_id: 10,
    category_id: 2,
  },
  {
    list_id: 1,
    ingredient_name: "tomato",
    qty: 8,
    unit_id: 1,
    category_id: 2,
  },
  {
    list_id: 1,
    ingredient_name: "beef",
    qty: 2,
    unit_id: 3,
    category_id: 5,
  },
  {
    list_id: 1,
    ingredient_name: "pork",
    qty: 4,
    unit_id: 3,
    category_id: 5,
  },
  {
    list_id: 1,
    ingredient_name: "sausage",
    qty: 2,
    unit_id: 10,
    category_id: 5,
  },
  {
    list_id: 2,
    ingredient_name: "apple",
    qty: 10,
    unit_id: 1,
    category_id: 1,
  },
  {
    list_id: 2,
    ingredient_name: "berry",
    qty: 1,
    unit_id: 10,
    category_id: 1,
  },
  {
    list_id: 2,
    ingredient_name: "grape",
    qty: 1,
    unit_id: 10,
    category_id: 1,
  },
  {
    list_id: 2,
    ingredient_name: "broccoli",
    qty: 1,
    unit_id: 1,
    category_id: 2,
  },
  {
    list_id: 2,
    ingredient_name: "garlic",
    qty: 15,
    unit_id: 1,
    category_id: 2,
  },
  {
    list_id: 2,
    ingredient_name: "mushroom",
    qty: 1,
    unit_id: 10,
    category_id: 2,
  },
  {
    list_id: 2,
    ingredient_name: "tomato",
    qty: 8,
    unit_id: 1,
    category_id: 2,
  },
  {
    list_id: 2,
    ingredient_name: "beef",
    qty: 2,
    unit_id: 3,
    category_id: 5,
  },
  {
    list_id: 2,
    ingredient_name: "pork",
    qty: 4,
    unit_id: 3,
    category_id: 5,
  },
  {
    list_id: 2,
    ingredient_name: "sausage",
    qty: 2,
    unit_id: 10,
    category_id: 5,
  },
  {
    list_id: 3,
    ingredient_name: "apple",
    qty: 10,
    unit_id: 1,
    category_id: 1,
  },
  {
    list_id: 3,
    ingredient_name: "berry",
    qty: 1,
    unit_id: 10,
    category_id: 1,
  },
  {
    list_id: 3,
    ingredient_name: "grape",
    qty: 1,
    unit_id: 10,
    category_id: 1,
  },
  {
    list_id: 3,
    ingredient_name: "broccoli",
    qty: 1,
    unit_id: 1,
    category_id: 2,
  },
  {
    list_id: 3,
    ingredient_name: "garlic",
    qty: 15,
    unit_id: 1,
    category_id: 2,
  },
  {
    list_id: 3,
    ingredient_name: "mushroom",
    qty: 1,
    unit_id: 10,
    category_id: 2,
  },
  {
    list_id: 3,
    ingredient_name: "tomato",
    qty: 8,
    unit_id: 1,
    category_id: 2,
  },
  {
    list_id: 3,
    ingredient_name: "beef",
    qty: 2,
    unit_id: 3,
    category_id: 5,
  },
  {
    list_id: 3,
    ingredient_name: "pork",
    qty: 4,
    unit_id: 3,
    category_id: 5,
  },
  {
    list_id: 3,
    ingredient_name: "sausage",
    qty: 2,
    unit_id: 10,
    category_id: 5,
  },
  {
    list_id: 4,
    ingredient_name: "apple",
    qty: 10,
    unit_id: 1,
    category_id: 1,
  },
  {
    list_id: 4,
    ingredient_name: "berry",
    qty: 1,
    unit_id: 10,
    category_id: 1,
  },
  {
    list_id: 4,
    ingredient_name: "grape",
    qty: 1,
    unit_id: 10,
    category_id: 1,
  },
  {
    list_id: 4,
    ingredient_name: "broccoli",
    qty: 1,
    unit_id: 1,
    category_id: 2,
  },
  {
    list_id: 4,
    ingredient_name: "garlic",
    qty: 15,
    unit_id: 1,
    category_id: 2,
  },
  {
    list_id: 4,
    ingredient_name: "mushroom",
    qty: 1,
    unit_id: 10,
    category_id: 2,
  },
  {
    list_id: 4,
    ingredient_name: "tomato",
    qty: 8,
    unit_id: 1,
    category_id: 2,
  },
  {
    list_id: 4,
    ingredient_name: "beef",
    qty: 2,
    unit_id: 3,
    category_id: 5,
  },
  {
    list_id: 4,
    ingredient_name: "pork",
    qty: 4,
    unit_id: 3,
    category_id: 5,
  },
  {
    list_id: 4,
    ingredient_name: "sausage",
    qty: 2,
    unit_id: 10,
    category_id: 5,
  },
  {
    list_id: 5,
    ingredient_name: "apple",
    qty: 10,
    unit_id: 1,
    category_id: 1,
  },
  {
    list_id: 5,
    ingredient_name: "berry",
    qty: 1,
    unit_id: 10,
    category_id: 1,
  },
  {
    list_id: 5,
    ingredient_name: "grape",
    qty: 1,
    unit_id: 10,
    category_id: 1,
  },
  {
    list_id: 5,
    ingredient_name: "broccoli",
    qty: 1,
    unit_id: 1,
    category_id: 2,
  },
  {
    list_id: 5,
    ingredient_name: "garlic",
    qty: 15,
    unit_id: 1,
    category_id: 2,
  },
  {
    list_id: 5,
    ingredient_name: "mushroom",
    qty: 1,
    unit_id: 10,
    category_id: 2,
  },
  {
    list_id: 5,
    ingredient_name: "tomato",
    qty: 8,
    unit_id: 1,
    category_id: 2,
  },
  {
    list_id: 5,
    ingredient_name: "beef",
    qty: 2,
    unit_id: 3,
    category_id: 5,
  },
  {
    list_id: 5,
    ingredient_name: "pork",
    qty: 4,
    unit_id: 3,
    category_id: 5,
  },
  {
    list_id: 5,
    ingredient_name: "sausage",
    qty: 2,
    unit_id: 10,
    category_id: 5,
  },
  {
    list_id: 6,
    ingredient_name: "apple",
    qty: 10,
    unit_id: 1,
    category_id: 1,
  },
  {
    list_id: 6,
    ingredient_name: "berry",
    qty: 1,
    unit_id: 10,
    category_id: 1,
  },
  {
    list_id: 6,
    ingredient_name: "grape",
    qty: 1,
    unit_id: 10,
    category_id: 1,
  },
  {
    list_id: 6,
    ingredient_name: "broccoli",
    qty: 1,
    unit_id: 1,
    category_id: 2,
  },
  {
    list_id: 6,
    ingredient_name: "garlic",
    qty: 15,
    unit_id: 1,
    category_id: 2,
  },
  {
    list_id: 6,
    ingredient_name: "mushroom",
    qty: 1,
    unit_id: 10,
    category_id: 2,
  },
  {
    list_id: 6,
    ingredient_name: "tomato",
    qty: 8,
    unit_id: 1,
    category_id: 2,
  },
  {
    list_id: 6,
    ingredient_name: "beef",
    qty: 2,
    unit_id: 3,
    category_id: 5,
  },
  {
    list_id: 6,
    ingredient_name: "pork",
    qty: 4,
    unit_id: 3,
    category_id: 5,
  },
  {
    list_id: 6,
    ingredient_name: "sausage",
    qty: 2,
    unit_id: 10,
    category_id: 5,
  },
  {
    list_id: 7,
    ingredient_name: "apple",
    qty: 10,
    unit_id: 1,
    category_id: 1,
  },
  {
    list_id: 7,
    ingredient_name: "berry",
    qty: 1,
    unit_id: 10,
    category_id: 1,
  },
  {
    list_id: 7,
    ingredient_name: "grape",
    qty: 1,
    unit_id: 10,
    category_id: 1,
  },
  {
    list_id: 7,
    ingredient_name: "broccoli",
    qty: 1,
    unit_id: 1,
    category_id: 2,
  },
  {
    list_id: 7,
    ingredient_name: "garlic",
    qty: 15,
    unit_id: 1,
    category_id: 2,
  },
  {
    list_id: 7,
    ingredient_name: "mushroom",
    qty: 1,
    unit_id: 10,
    category_id: 2,
  },
  {
    list_id: 7,
    ingredient_name: "tomato",
    qty: 8,
    unit_id: 1,
    category_id: 2,
  },
  {
    list_id: 7,
    ingredient_name: "beef",
    qty: 2,
    unit_id: 3,
    category_id: 5,
  },
  {
    list_id: 7,
    ingredient_name: "pork",
    qty: 4,
    unit_id: 3,
    category_id: 5,
  },
  {
    list_id: 7,
    ingredient_name: "sausage",
    qty: 2,
    unit_id: 10,
    category_id: 5,
  },
  {
    list_id: 8,
    ingredient_name: "apple",
    qty: 10,
    unit_id: 1,
    category_id: 1,
  },
  {
    list_id: 8,
    ingredient_name: "berry",
    qty: 1,
    unit_id: 10,
    category_id: 1,
  },
  {
    list_id: 8,
    ingredient_name: "grape",
    qty: 1,
    unit_id: 10,
    category_id: 1,
  },
  {
    list_id: 8,
    ingredient_name: "broccoli",
    qty: 1,
    unit_id: 1,
    category_id: 2,
  },
  {
    list_id: 8,
    ingredient_name: "garlic",
    qty: 15,
    unit_id: 1,
    category_id: 2,
  },
  {
    list_id: 8,
    ingredient_name: "mushroom",
    qty: 1,
    unit_id: 10,
    category_id: 2,
  },
  {
    list_id: 8,
    ingredient_name: "tomato",
    qty: 8,
    unit_id: 1,
    category_id: 2,
  },
  {
    list_id: 8,
    ingredient_name: "beef",
    qty: 2,
    unit_id: 3,
    category_id: 5,
  },
  {
    list_id: 8,
    ingredient_name: "pork",
    qty: 4,
    unit_id: 3,
    category_id: 5,
  },
  {
    list_id: 8,
    ingredient_name: "sausage",
    qty: 2,
    unit_id: 10,
    category_id: 5,
  },
  {
    list_id: 9,
    ingredient_name: "apple",
    qty: 10,
    unit_id: 1,
    category_id: 1,
  },
  {
    list_id: 9,
    ingredient_name: "berry",
    qty: 1,
    unit_id: 10,
    category_id: 1,
  },
  {
    list_id: 9,
    ingredient_name: "grape",
    qty: 1,
    unit_id: 10,
    category_id: 1,
  },
  {
    list_id: 9,
    ingredient_name: "broccoli",
    qty: 1,
    unit_id: 1,
    category_id: 2,
  },
  {
    list_id: 9,
    ingredient_name: "garlic",
    qty: 15,
    unit_id: 1,
    category_id: 2,
  },
  {
    list_id: 9,
    ingredient_name: "mushroom",
    qty: 1,
    unit_id: 10,
    category_id: 2,
  },
  {
    list_id: 9,
    ingredient_name: "tomato",
    qty: 8,
    unit_id: 1,
    category_id: 2,
  },
  {
    list_id: 9,
    ingredient_name: "beef",
    qty: 2,
    unit_id: 3,
    category_id: 5,
  },
  {
    list_id: 9,
    ingredient_name: "pork",
    qty: 4,
    unit_id: 3,
    category_id: 5,
  },
  {
    list_id: 9,
    ingredient_name: "sausage",
    qty: 2,
    unit_id: 10,
    category_id: 5,
  },
];
