module.exports = [
  {
    user_id: 1,
    ingredient_name: "potato",
    qty: "4",
    unit_id: 1,
    category_id: 2,
    shelf_life: "",
  },
  {
    user_id: 1,
    ingredient_name: "orange",
    qty: "10",
    unit_id: 1,
    category_id: 1,
    shelf_life: "",
  },
  {
    user_id: 1,
    ingredient_name: "melon",
    qty: "1",
    unit_id: 1,
    category_id: 1,
    shelf_life: "",
  },
  {
    user_id: 1,
    ingredient_name: "cucumber",
    qty: "4",
    unit_id: 1,
    category_id: 2,
    shelf_life: "",
  },
  {
    user_id: 1,
    ingredient_name: "zucchini",
    qty: "3",
    unit_id: 1,
    category_id: 2,
    shelf_life: "",
  },
  {
    user_id: 1,
    ingredient_name: "fish",
    qty: "4",
    unit_id: 3,
    category_id: 5,
    shelf_life: "",
  },
  {
    user_id: 1,
    ingredient_name: "bacon",
    qty: "4",
    unit_id: 3,
    category_id: 5,
    shelf_life: "",
  },
  {
    user_id: 3,
    ingredient_name: "potato",
    qty: "4",
    unit_id: 1,
    category_id: 2,
    shelf_life: "",
  },
  {
    user_id: 3,
    ingredient_name: "orange",
    qty: "10",
    unit_id: 1,
    category_id: 1,
    shelf_life: "",
  },
  {
    user_id: 3,
    ingredient_name: "melon",
    qty: "1",
    unit_id: 1,
    category_id: 1,
    shelf_life: "",
  },
  {
    user_id: 3,
    ingredient_name: "cucumber",
    qty: "4",
    unit_id: 1,
    category_id: 2,
    shelf_life: "",
  },
  {
    user_id: 3,
    ingredient_name: "zucchini",
    qty: "3",
    unit_id: 1,
    category_id: 2,
    shelf_life: "",
  },
  {
    user_id: 3,
    ingredient_name: "fish",
    qty: "4",
    unit_id: 3,
    category_id: 5,
    shelf_life: "",
  },
  {
    user_id: 3,
    ingredient_name: "bacon",
    qty: "4",
    unit_id: 3,
    category_id: 5,
    shelf_life: "",
  },
  {
    user_id: 2,
    ingredient_name: "potato",
    qty: "4",
    unit_id: 1,
    category_id: 2,
    shelf_life: "",
  },
  {
    user_id: 2,
    ingredient_name: "orange",
    qty: "10",
    unit_id: 1,
    category_id: 1,
    shelf_life: "",
  },
  {
    user_id: 2,
    ingredient_name: "melon",
    qty: "1",
    unit_id: 1,
    category_id: 1,
    shelf_life: "",
  },
  {
    user_id: 2,
    ingredient_name: "cucumber",
    qty: "4",
    unit_id: 1,
    category_id: 2,
    shelf_life: "",
  },
  {
    user_id: 2,
    ingredient_name: "zucchini",
    qty: "3",
    unit_id: 1,
    category_id: 2,
    shelf_life: "",
  },
  {
    user_id: 2,
    ingredient_name: "fish",
    qty: "4",
    unit_id: 3,
    category_id: 5,
    shelf_life: "",
  },
  {
    user_id: 2,
    ingredient_name: "bacon",
    qty: "4",
    unit_id: 3,
    category_id: 5,
    shelf_life: "",
  },
  {
    user_id: 2,
    ingredient_name: "potato",
    qty: "4",
    unit_id: 1,
    category_id: 2,
    shelf_life: "",
  },
  {
    user_id: 4,
    ingredient_name: "orange",
    qty: "10",
    unit_id: 1,
    category_id: 1,
    shelf_life: "",
  },
  {
    user_id: 4,
    ingredient_name: "melon",
    qty: "1",
    unit_id: 1,
    category_id: 1,
    shelf_life: "",
  },
  {
    user_id: 4,
    ingredient_name: "cucumber",
    qty: "4",
    unit_id: 1,
    category_id: 2,
    shelf_life: "",
  },
  {
    user_id: 4,
    ingredient_name: "zucchini",
    qty: "3",
    unit_id: 1,
    category_id: 2,
    shelf_life: "",
  },
  {
    user_id: 4,
    ingredient_name: "fish",
    qty: "4",
    unit_id: 3,
    category_id: 5,
    shelf_life: "",
  },
  {
    user_id: 4,
    ingredient_name: "bacon",
    qty: "4",
    unit_id: 3,
    category_id: 5,
    shelf_life: "",
  },
];
